development:
  adapter: postgresql
  encoding: unicode
  database: shacs_development
  pool: 5
  username: shacs
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shacs_test
  pool: 5
  username: shacs
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: shacs_production
  pool: 5
  username: shacs
  password:

